### ISSUE TITLE
Alerts will alert on transitive alert-job failures, will also not alert on submission failures. 

### ISSUE THREAD

**Issue by mccabete** [Earth-Information-System/fireatlas#148]
Today the alert bot alerted three times:

<img width="741" alt="image" src="https://github.com/user-attachments/assets/922b1d6e-5c73-4ec1-851b-c8cfb7475d94">

Those alerts correspond to three outages for the alert-bot-action, [here](https://github.com/Earth-Information-System/fireatlas/actions/runs/10991440672),[ here](https://github.com/Earth-Information-System/fireatlas/actions/runs/10988876883) and [here](https://github.com/Earth-Information-System/fireatlas/actions/runs/10988165282). Those actions seemed to fail for transient reasons, because they worked fine later. It is a little weird that the job to check for failures, "failed", but still sent a slack alert. 

It looks like alerts didn't trigger for the NRT update job  that failed [here](https://github.com/Earth-Information-System/fireatlas/actions/runs/10995129976). My guess is because the job failed at submission, and didn't acquire a status of "failed". That action also seemed to fail for transient reasons, because it too worked fine after it was submitted again. 

The questions we want to resolve:

- Can we filter out alerts for transient failures? If alerts are too common, we'll miss the big outages. 
- Do we want the alerts-job alerting for itself? While it would be good to know if it breaks entirely, it seems to be generating the most noise right now. 
- We can't detect failures at the submission stage to DPS. This time it was a transient failure, unclear if it will always be. This might be specifically relevant as the DPS moves to a new release.

**Comment by zebbecker** [comment]
I see what you mean about not being able to detect failures at submission. I can add the Slack webhook to the end of the scheduler actions as well, which would alert us if the submission fails. Because yeah, as you say checking for failed DPS jobs does us no good if our job never got accepted in the first place. 

Will follow up on the noise issue. We do need alert-jobs to alert for itself, but it should not be failing this much. Both the failures of that job and the failures to submit scheduled jobs come from MAAP API invalid responses, as far as I can tell so far. Hopefully fixing that will fix the spam.

**Comment by zebbecker** [comment]
This ended up being two related issues- both are now resolved. 

1. Intermittent failures have been fixed by the MAAP team. We will still get alerts if something like that happens again, but that is my desired behavior. Can revisit if we are still getting too much noise going forward. 

2. #153 adds slack alerts for jobs that fail to submit, like the NRT update job pointed out above that never sent a notification.
